create extension if not exists pgcrypto;

create table if not exists public.raw_materials (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  brand text,
  vendor text,
  unit text,
  unit_price numeric(12, 2) not null default 0,
  stock numeric(12, 3) not null default 0,
  safe_stock numeric(12, 3) not null default 50,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  price numeric(12, 2) not null default 0,
  cost numeric(12, 2) not null default 0,
  stock numeric(12, 3) not null default 0,
  shelf_life integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_recipes (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  material_id bigint not null references public.raw_materials(id),
  qty_per_unit numeric(12, 3) not null,
  note text,
  created_at timestamptz not null default now(),
  unique (product_id, material_id)
);

create table if not exists public.inbound_records (
  id bigint generated by default as identity primary key,
  material_id bigint not null references public.raw_materials(id),
  qty numeric(12, 3) not null,
  unit_price numeric(12, 2) not null default 0,
  batch_number text,
  expiry_date date,
  note text,
  created_at timestamptz not null default now(),
  created_by uuid
);

create table if not exists public.production_logs (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id),
  qty numeric(12, 3) not null,
  batch_number text,
  expiry_date date,
  note text,
  created_at timestamptz not null default now(),
  created_by uuid
);

create table if not exists public.sales_records (
  id bigint generated by default as identity primary key,
  product_name text not null,
  qty numeric(12, 3) not null default 0,
  price numeric(12, 2) not null default 0,
  amount numeric(12, 2) not null default 0,
  sale_date timestamptz,
  order_id text,
  created_at timestamptz not null default now(),
  created_by uuid
);

create table if not exists public.inventory_adjustments (
  id bigint generated by default as identity primary key,
  material_id bigint not null references public.raw_materials(id),
  old_stock numeric(12, 3) not null,
  new_stock numeric(12, 3) not null,
  diff numeric(12, 3) not null,
  reason text,
  created_at timestamptz not null default now(),
  created_by uuid
);

create table if not exists public.profiles (
  id uuid primary key,
  email text unique,
  display_name text,
  role text not null default 'staff',
  location_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_raw_materials_name on public.raw_materials(name);
create index if not exists idx_products_name on public.products(name);
create index if not exists idx_inbound_records_material_id on public.inbound_records(material_id);
create index if not exists idx_production_logs_product_id on public.production_logs(product_id);
create index if not exists idx_inventory_adjustments_material_id on public.inventory_adjustments(material_id);
